[nitpick.meta]
name = "Flake8 style"

[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.exclude",]

["setup.cfg".flake8]
format = "wemake"
show-source = true
statistics = false
doctests = true
enable-extensions = "G"
strictness = "long"
docstring-style = "numpy"
max-line-length = 120
max-try-body-length = 5
max-complexity = 6
inline-quotes = "double"
exclude = ".git,__pycache__,.venv,.eggs,*.egg,.tox,build"
ignore = "D100,D101,D102,D103,D104,D107,D202,D203,D401,E203,E402,E501,W503,WPS326,WPS318"
per-file-ignores = "test_*.py:S101,DAR101"