[nitpick.meta]
name = "Flake8 style"

["pyproject.toml".tool.poetry.group.dev.dependencies]
flake8 = "*"
bandit = "*"
flake8-bandit = "*"
wemake-python-styleguide = "*"

[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.exclude",]

["setup.cfg".flake8]
exclude = ".git,__pycache__,.venv,.eggs,*.egg"
ignore = "D100,D103,D107,D202,D203,D401,E203,E402,E501,W503"
per-file-ignores = "test_*.py:S101,DAR101"
max-line-length = 120
inline-quotes = "double"
exclude = ".tox,build"

