[nitpick.meta]
name = "isort"

["setup.cfg".isort]
profile="wemake"
line_length = 120
skip = ".tox,build"
known_first_party = "tests"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true