[nitpick.meta]
name = "pre-commit hook style"

[[".pre-commit-config.yaml".repos]]
repo = "local"

[[".pre-commit-config.yaml".repos.hooks]]
id = "flake8"
name = "Run flake8"
entry = "poetry run flake8"
language = "python"
types_or = ["python", "pyi"]
require_serial = true

[[".pre-commit-config.yaml".repos.hooks]]
id = "mypy"
name = "Run mypy"
entry = "poetry run mypy"
language = "python"
types_or = ["python", "pyi"]
require_serial = true
