[nitpick.meta]
name = "Django styles"

[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.exclude", "bandit.exclude"]

["pyproject.toml".tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "service.settings"

["setup.cfg".flake8]
ignore = "D100,D101,D102,D103,D104,D105,D106,D107,D401,X100,W504,RST303,RST304,DAR103,DAR203,WPS306"
per-file-ignores = 'service/settings/*.py:WPS226,WPS407,WPS412,WPS432 **/migrations/*.py:WPS102,WPS114,WPS318,WPS326,WPS432,WPS440 tests/*.py:S101,WPS432 service/__init__.py:WPS412,WPS410 manage.py:WPS433,WPS326,C812'

["setup.cfg".bandit]
exclude = "manage.py,"

["setup.cfg".mypy]
plugins = 'mypy_django_plugin.main, mypy_drf_plugin.main'

["setup.cfg"."mypy.plugins.django-stubs"]
django_settings_module = 'service.settings'
