[nitpick.meta]
name = "mypy styles"

["setup.cfg".mypy]
allow_redefinition = false
check_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
local_partial_types = true
no_implicit_optional = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
plugins = 'mypy_django_plugin.main, mypy_drf_plugin.main'

["setup.cfg"."mypy.plugins.django-stubs"]
django_settings_module = 'service.settings'
